### ISSUE TITLE
Cannot resolve module 'react-addons-transition-group'

### ISSUE THREAD

**Issue by worg** [thorgate/tg-modal#10]
When doing an import of 'tg-modal' I get
```
ERROR in ./~/tg-modal/dist/remote/TimedCSSTransitionGroup.js
Module not found: Error: Cannot resolve module 'react-addons-transition-group'
```

**Comment by schryer** [comment]
You seem to be using react 0.13.  This means that you need to import tg-modal as such:

import TgModal from 'tg-modal/v013';

If you ever upgrade to React version 0.14, you will need to remove the /v013 part.

**Comment by OdifYltsaeb** [comment]
Go David,Go!

**Comment by worg** [comment]
I'm using React 0.14, if I add v013 the modal works but I get a lot of deprecation warnings, I don't know if this could be related to the fact that I'm using the react-addons-transition-group module in another part of the same project [and the modal is inside a child view of a ReactCSSTransitionGroup]

**Comment by worg** [comment]
It seems that doing an `npm i react-addons-transition-group` solves the error
