### ISSUE TITLE
Changing background color

### ISSUE THREAD

**Issue by giouxel** [thorgate/tg-modal#137]
Please help me with changing the background from rgba(0, 0, 0, 0.85) to rgba(0, 0, 0, 0.15)

**Comment by metsavaht** [comment]
Do you mean the backdrop color? If yes then you can override `.tg-modal-backdrop` class, e.g when using .scss
```
@import `~tg-modal/dist/default.scss`;

.tg-modal-backdrop {
    background: rgba(0, 0, 0, 0.15);
}
```

**Comment by Jyrno42** [comment]
Feel free to open another issue if the comment above does not resolve your issue
