### ISSUE TITLE
Add className to ModalDialog

### ISSUE THREAD

**Issue by cvetanov** [thorgate/tg-modal#22]
Hi,

What do you think about adding a custom className to the ModalDialog component the same way it is done for the ModalBody component with preserving the default classNames through defaultProps.

I can make a PR and do that if you think it's okay.

Regards,
Goce

**Comment by cvetanov** [comment]
Furthermore, the ModalHeader's render method can be improved by moving the typeof children check first.
This way, the check for creating a close button will not be executed all the time, only when needed.

**Comment by Jyrno42** [comment]
would be happy to review PRs for both of these issues :)
