### ISSUE TITLE
Does not this support IE10 ?

### ISSUE THREAD

**Issue by anujsharma-bbd** [thorgate/tg-modal#27]
I am facing issue on IE10 when going to open .

see the error:- 
![image](https://cloud.githubusercontent.com/assets/18569992/21723073/224f451e-d455-11e6-9527-73b0d8757118.png)

**Comment by anujsharma-bbd** [comment]
any update on this ? please have look into.

**Comment by Jyrno42** [comment]
Can you please provide a codepen/jsbin example, we are having a tough time replicating this.

**Comment by Jyrno42** [comment]
closed since there was no feedback
