### ISSUE TITLE
Integration with Bootstrap app

### ISSUE THREAD

**Issue by azfx** [thorgate/tg-modal#30]
tg-modal uses same class `.modal` as used by bootstrap modals. This makes it unusable on web app built using bootstrap.

**Comment by Jyrno42** [comment]
Current workaround we use internally is to not include bootstrap modal styles/js in those applications.

The current plan is to fix it in 0.8 by prepending `.tg-` for our css classes.

**Comment by metsavaht** [comment]
Increases usability with other modal library's that might to something similar.
Seems like a good plan to be used for our other projects as well.
